language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run lint
  - npm run style-lint
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    firebase deploy --token "$FIREBASE_TOKEN"
