language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run lint
  - npm run stylelint
deploy:
  provider: firebase
  token:
    secure: "lWfTIK9Vg6L3ggY5kwJBaA8aFB7yy+t1Ntkis4Wqdnxde0SDrodei71tu0pt8v+/7vPDg3Do9zcTxWEPtoR6qd1gUhjEs1DLkEiq4+e4O/LkdqszC7SRi1EDKQRU8M6owztmrTmEbjuT4On7Ds1NLIics4D18e1xGI1gu7VCdEYOcl7azb2W0IkwleYMfn4dg61l02yp3ilQPfylyc/KQLxULkY87p7fxMT7dBuZVZtFVfY9AA1J5WctiMC3dsagn3oTru+projajEySiirGO5uPd6sI7Eb1LCGFN9DMeuy21ItKVtkPwVGgboBD/wOyrfbkMQySjren4Nmms+RWzWiXuaFtWHDARjxQR7d3nKjStyMX0KQ7iZLOBRYhpnf82PUhD5E6e8VHLCfk9WsHirR1nHykcwG57AUuq3m+1Qlvre6JEwXlJHZY7B1Od89bSxNvL41mhl4INbl3Nx3/H4PcxWxLDt9ZvHLF/SimtO2kA3Q8Z/akMVwa4OmT12ia6JPdLZ/qU9whtOkzEHfr6mpnQBNwuKTNw6tL8I6pnYzS73gQoySWdScFMLUuBIA0YZ2zFeOmNLCSjAKzyEZFrm/cEb4lJiWGVtyUWoI22TShOEzQSvRh715TYyLqlslXKu4R7LvNs3Dhr/9gf6mjIb5t4PlUHJsNpOjYcdq9tjw="
  on:
    branch: master
